let datapath = new URL("..", import.meta.url).href
let icon = `${datapath}assets/icon`

export default [
    `${icon}/logo.png`,
    `${icon}/momo.svg`,
    //`${icon}/ko-fi.webp`,
    `${icon}/paypal.png`,
    `${icon}/about-us/balaclava.png`,
    `${icon}/about-us/dmitryfisk.png`,
    `${icon}/about-us/elainadacatto.png`,
    `${icon}/about-us/flirip.png`,
    `${icon}/about-us/legnatbird.png`,
    `${icon}/about-us/soulmare.png`,
    `${icon}/about-us/unproductive.webp`,
    `${icon}/plugins-icons/button-blue-essence.png`,
    `${icon}/plugins-icons/button-blue-essence-click.png`,
    `${icon}/plugins-icons/button-blue-essence-hover.png`,
    `${icon}/plugins-icons/button-open-chests.png`,
    `${icon}/plugins-icons/button-open-chests-click.png`,
    `${icon}/plugins-icons/button-open-chests-hover.png`,
    `${icon}/plugins-icons/button-refresh.png`,
    `${icon}/plugins-icons/button-refresh-click.png`,
    `${icon}/plugins-icons/button-refresh-hover.png`,
    `${icon}/plugins-icons/elainacb.png`,
    `${icon}/plugins-icons/reroll_button.png`,
    `${datapath}assets/champs/miku.png`,
    `${datapath}assets/champs/miku_preview.png`,
    "https://avatars.githubusercontent.com/u/29869255",
    "https://avatars.githubusercontent.com/u/43145883",
    "https://avatars.githubusercontent.com/u/38210249",
    "https://avatars.githubusercontent.com/u/8694498",
    "https://avatars.githubusercontent.com/u/45071533",
    "https://avatars.githubusercontent.com/u/59478113",
]